### ISSUE TITLE
"Poliglot" misspelling

### ISSUE THREAD

**Issue by NeverN1ght** [BinaryStudioAcademy/bsa-2018-polyglot#6]
https://github.com/BinaryStudioAcademy/bsa-2018-polyglot/blob/10b807e0090561701593b65c834c62ce75eb3a80/backend/Polyglot.BusinessLogic/Implementations/HttpServices/HttpService.cs#L33
Correct name - "Polyglot", not "Poliglot"

**Comment by GuziyV** [comment]
Thank you, fixed
